src/cmds/core/other.py
=> Remove message.delete() as not required for slash commands

.github/workflows/deploy.yaml
=> Update deploy.yaml to use contains instead of endsWith

pyproject.toml
=> Update version to 1.0.2 in pyproject.toml

poetry.lock, pyproject.toml, src/__init__.py, src/cmds/core/ping.py, src/core/config.py
doc.
Added VERSION to the Global settings and use it in Sentry and ping command.
=> Sentry release

src/helpers/ban.py
- Fix channel in ban helper
doc.
=> Update ban helper to send message to correct channel

src/helpers/ban.py, tests/conftest.py, tests/helpers.py, tests/src/helpers/test_ban.py
Refactor ban function to validate author exists before checking author ID
Add a check for author existence.
doc.
=> Refactor ban function to validate author exists before checking author ID

src/cmds/core/other.py
URGENT: Users can post into any channel
doc.
=> Remove no hints from other channels

src/cmds/core/user.py
=> Add htb_id in whois

src/cmds/core/ban.py, src/cmds/core/user.py
Solves #20, add a warn with a weight of 0, containing the reason(and if applicable, ban duration) to the users history
doc.
=> Add infractions to record on ban/kick

src/cmds/core/mute.py
Closes #46, uses the discord timeout function to put the burden onto discord to ensure that a user remains muted for the set duration
doc.
=> fix mute evasion

src/cmds/core/user.py
=> Handle whois with user_id correctly

src/helpers/ban.py
Call DM member prior to ban, since if called after it will always have a perm error due to no shared guild 
doc.
=> Fix ban DM

src/helpers/ban.py
Add a new line to the perm error...... just looks nicer
doc.
=> newline to perm error

src/cmds/core/other.py
links to how to get support
doc.
=> add /support command

src/core/config.py
=> Refactor Roles class in config.py to remove unnecessary rank positions

src/core/config.py
=> Remove references for deleted roles

src/cmds/core/verify.py, src/core/config.py, src/helpers/verification.py
Add manual certification validation
doc.
=> Manual Cert Validation

src/cmds/core/verify.py, src/core/config.py, src/helpers/verification.py
=> CDSA + Ctx.reply -> CTX.respond

src/helpers/verification.py
=> Fix CPTS Verification

src/cmds/core/fun.py
=> Use working site

poetry.lock, pyproject.toml
=> Update Sentry to 1.45.0

src/helpers/ban.py
Improvement of the ban display
Implement issue #54  . Changed the display of the Ban request log
doc.
=> [FEATURE] Issue #54 - Change the log to DisplayName (username)

src/views/bandecisionview.py
HTB Discord admin requested (in #bot-dev) for keeping the buttons active after sanctioning an action. This is a minor change for #109 
doc.
=> [FEATURE] - Keep buttons active

tests/src/cmds/core/test_user.py
It seems that with adding the code from the change requested during review was missing a parenthesis, causing the build test to fail (#115) breaking the build from main branch
doc.
=> [BUGFIX] Fix failing test due to missing parenthesis from PR #115

.github/workflows/test.yaml, CONTRIBUTING.md, src/bot.py, src/cmds/core/user.py, src/cmds/core/verify.py, src/helpers/ban.py, src/utils/pagination.py, tests/helpers.py, tests/src/cmds/core/test_user.py
- **🐛 (src/helpers/ban.py): Fix issue with Guild.ban() arguments**
- **🎨 (src): Typos, data types, etc.**
- **👷 (.github/workflows/test.yaml): Enable test workflow on PR**
doc.
=> Fix ban and other minor changes

.coveragerc, codecov.yml
Omit and ignore `tests/` folder from code coverage.
doc.
=> Code coverage improvements

src/helpers/duration.py
Banning a user for the duration of `1 year` resulted in a ban of 1 second
doc.
=> [BUGFIX] - Added more arbitrary measures of time options for _year_

src/cmds/core/ban.py, src/cmds/core/user.py, src/helpers/ban.py, tests/src/cmds/core/test_ban.py, tests/src/cmds/core/test_user.py
Current: we add an infraction and a note with the evidence causing a duplicate entry. 
Future: We now only add the evidence in the infraction table, resulting in a cleaner record. Also made the message in the infraction to be more like the message when added by a ban
doc.
=> [IMPROVEMENT] - Deduplicate evidence/note

src/cmds/core/channel.py
We will now purge the amount of messages sent through in the count. Not count + 1. Fixes #154
doc.
Fixes #154
=> Cleanup purges count
